### ISSUE TITLE
Reshape error on own dataset

### ISSUE THREAD

**Issue by polar99** [Stick-To/Object-Detection-API-Tensorflow#28]
Train CenterNet on own dataset. The dataset is converted to tfrecord format with tfrecord_voc_utils.py.

But I have got the following errors. It seems that the error is from reshape(). 
I need your help. @Stick-To 
`Traceback (most recent call last):
  File "E:/AI/project/GitHub/CenterNet_ObjectAsPoints/CenterNet-tensorflow-master/train.py", line 76, in <module>
    mean_loss = centernet.train_one_epoch(lr)

  File "E:\AI\project\GitHub\CenterNet_ObjectAsPoints\CenterNet-tensorflow-master\CenterNet.py", line 295, in train_one_epoch

    _, loss = self.sess.run([self.train_op, self.loss], feed_dict={self.lr: lr})
  File "E:\AI\project\GitHub\CenterNet_ObjectAsPoints\CenterNet-tensorflow-master\venv\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)

  File "E:\AI\project\GitHub\CenterNet_ObjectAsPoints\CenterNet-tensorflow-master\venv\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)

  File "E:\AI\project\GitHub\CenterNet_ObjectAsPoints\CenterNet-tensorflow-master\venv\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)

  File "E:\AI\project\GitHub\CenterNet_ObjectAsPoints\CenterNet-tensorflow-master\venv\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)

tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 786432 values, but the requested shape has 262144

	 [[{{node Reshape_2}}]]
	 [[node IteratorGetNext (defined at E:\AI\project\GitHub\CenterNet_ObjectAsPoints\CenterNet-tensorflow-master\CenterNet.py:63) ]]`

**Comment by polar99** [comment]
I have commented the code from tfrecord_voc_utils.py in line [106](https://github.com/Stick-To/Object-Detection-API-Tensorflow/blob/44cd28c48e98da936e585b5dd3c48ac5d545125e/utils/tfrecord_voc_utils.py#L106).

It works.

`# images = tf.cast(tf.reshape(images, shape), tf.float32)`
`images = tf.cast(images, tf.float32)`
