### ISSUE TITLE
Error while training my own data

### ISSUE THREAD

**Issue by keithyh** [Stick-To/Object-Detection-API-Tensorflow#31]
------------------------- epoch 0 -------------------------
reduce lr, lr= 0.0001 now
Traceback (most recent call last):

  File "<ipython-input-1-102bddff4976>", line 1, in <module>
    runfile('D:/bu/Object-Detection-API-Tensorflow-master/Object-Detection-API-Tensorflow-master/testcenternet.py', wdir='D:/bu/Object-Detection-API-Tensorflow-master/Object-Detection-API-Tensorflow-master')

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/bu/Object-Detection-API-Tensorflow-master/Object-Detection-API-Tensorflow-master/testcenternet.py", line 76, in <module>
    mean_loss = centernet.train_one_epoch(lr)

  File "D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py", line 295, in train_one_epoch
    _, loss = self.sess.run([self.train_op, self.loss], feed_dict={self.lr: lr})

  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)

  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)

  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)

  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)

DataLossError: 2 root error(s) found.
  (0) Data loss: corrupted record at 0
	 [[node IteratorGetNext (defined at D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py:63) ]]
	 [[center_detector/cond_59/SparseToDense/_829]]
  (1) Data loss: corrupted record at 0
	 [[node IteratorGetNext (defined at D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py:63) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node IteratorGetNext:
 IteratorV2 (defined at D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\utils\tfrecord_voc_utils.py:176)

Input Source operations connected to node IteratorGetNext:
 IteratorV2 (defined at D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\utils\tfrecord_voc_utils.py:176)

Original stack trace for 'IteratorGetNext':
  File "D:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\lib\site-packages\spyder_kernels\console\__main__.py", line 11, in <module>
    start.main()
  File "D:\Anaconda3\lib\site-packages\spyder_kernels\console\start.py", line 310, in main
    kernel.start()
  File "D:\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "D:\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "D:\Anaconda3\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "D:\Anaconda3\lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "D:\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Anaconda3\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "D:\Anaconda3\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "D:\Anaconda3\lib\site-packages\tornado\gen.py", line 781, in inner
    self.run()
  File "D:\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "D:\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "D:\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "D:\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "D:\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "D:\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "D:\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2848, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "D:\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3049, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3220, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-102bddff4976>", line 1, in <module>
    runfile('D:/bu/Object-Detection-API-Tensorflow-master/Object-Detection-API-Tensorflow-master/testcenternet.py', wdir='D:/bu/Object-Detection-API-Tensorflow-master/Object-Detection-API-Tensorflow-master')
  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)
  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "D:/bu/Object-Detection-API-Tensorflow-master/Object-Detection-API-Tensorflow-master/testcenternet.py", line 64, in <module>
    centernet = net.CenterNet(config, trainset_provider)
  File "D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py", line 44, in __init__
    self._define_inputs()
  File "D:\bu\Object-Detection-API-Tensorflow-master\Object-Detection-API-Tensorflow-master\CenterNet.py", line 63, in _define_inputs
    self.images, self.ground_truth = self.train_iterator.get_next()
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 426, in get_next
    output_shapes=self._structure._flat_shapes, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 1974, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

Please could you tell my why this error occured?

**Comment by berit99** [comment]
Having the same issue, could you share the solution or the reason for this error?

**Comment by sxp0100** [comment]
chang 'pad_truth_to': in test.py to a right vale may work, my value is 190 ,
