### ISSUE TITLE
custom dataset image size problem

### ISSUE THREAD

**Issue by QianSunCN** [Stick-To/Object-Detection-API-Tensorflow#32]
Hello,Thank you for your code.  
When I run this code, it works on VOC dataset. When I usu my own custom dataset with only one class, these image are 1000x1400 size，some errors have occurred...
------------------------- epoch 0 -------------------------
Traceback (most recent call last):
  File "D:\Software\python\anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "D:\Software\python\anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\Software\python\anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 4200000 values, but the requested shape has 1400000
	 [[{{node Reshape_2}}]]
	 [[{{node IteratorGetNext}}]]
	 [[{{node SparseToDense_15}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:/deeplearning/Object-Detection-API-Tensorflow-master/testYOLOv3.py", line 77, in <module>
    mean_loss = testnet.train_one_epoch(lr)
  File "H:\deeplearning\Object-Detection-API-Tensorflow-master\YOLOv3.py", line 451, in train_one_epoch
    feed_dict={self.lr: lr})
  File "D:\Software\python\anaconda\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "D:\Software\python\anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Software\python\anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "D:\Software\python\anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 4200000 values, but the requested shape has 1400000
	 [[node Reshape_2 (defined at H:\deeplearning\Object-Detection-API-Tensorflow-master\YOLOv3.py:41) ]]
	 [[node IteratorGetNext (defined at H:\deeplearning\Object-Detection-API-Tensorflow-master\YOLOv3.py:72) ]]
	 [[node SparseToDense_15 (defined at H:\deeplearning\Object-Detection-API-Tensorflow-master\YOLOv3.py:127) ]]

Caused by op 'Reshape_2', defined at:
  File "H:/deeplearning/Object-Detection-API-Tensorflow-master/testYOLOv3.py", line 70, in <module>
    testnet = yolov3.YOLOv3(config, trainset_provider)
  File "H:\deeplearning\Object-Detection-API-Tensorflow-master\YOLOv3.py", line 41, in __init__
    self.priors.append(tf.reshape(tf.constant(priors[i], dtype=tf.float32)/self.stride[i], [1, 1, -1, 2]))
  File "D:\Software\python\anaconda\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 8462, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "D:\Software\python\anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "D:\Software\python\anaconda\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Software\python\anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "D:\Software\python\anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 4200000 values, but the requested shape has 1400000

**Comment by Stick-To** [comment]
is it Gray Scale Image？

**Comment by Stick-To** [comment]
https://github.com/Stick-To/Object-Detection-API-Tensorflow/issues/28

**Comment by QianSunCN** [comment]
> is it Gray Scale Image？

RGB images with sieze 1000x1400x3, is it size too large?

**Comment by Stick-To** [comment]
may #28 could help you

**Comment by QianSunCN** [comment]
> may #28 could help you

Thank you very much, I modify the code by #28, it works.
