### ISSUE TITLE
Error in training Centernet

### ISSUE THREAD

**Issue by KapilM26** [Stick-To/Object-Detection-API-Tensorflow#53]
When I try to train Centernet with custom dataset (generated tfrecords) i get this issue:
```
Traceback (most recent call last):
  File "/home/kapil/anaconda3/envs/run_stylegan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/kapil/anaconda3/envs/run_stylegan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/kapil/anaconda3/envs/run_stylegan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [52,1] vs. shape[2] = [51,1]
	 [[{{node concat_1}}]]
	 [[IteratorGetNext]]
	 [[center_detector/cond_23/SparseToDense/_349]]
  (1) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [52,1] vs. shape[2] = [51,1]
	 [[{{node concat_1}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testcenternet.py", line 69, in <module>
    mean_loss = centernet.train_one_epoch(lr)
  File "/home/kapil/Object-Detection-API-Tensorflow/CenterNet.py", line 295, in train_one_epoch
    _, loss = self.sess.run([self.train_op, self.loss], feed_dict={self.lr: lr})
  File "/home/kapil/anaconda3/envs/run_stylegan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/kapil/anaconda3/envs/run_stylegan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/kapil/anaconda3/envs/run_stylegan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/kapil/anaconda3/envs/run_stylegan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [52,1] vs. shape[2] = [51,1]
	 [[{{node concat_1}}]]
	 [[IteratorGetNext]]
	 [[center_detector/cond_23/SparseToDense/_349]]
  (1) Invalid argument: ConcatOp : Dimensions of inputs should match: shape[0] = [52,1] vs. shape[2] = [51,1]
	 [[{{node concat_1}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.
```
please help!

**Comment by lvZic** [comment]
have u fixed it?  I met the same problem.
