### ISSUE TITLE
Paddings must be non-negative: 0 -49

### ISSUE THREAD

**Issue by lvZic** [Stick-To/Object-Detection-API-Tensorflow#54]
------------------------- epoch 0 -------------------------
Traceback (most recent call last):
File "/mnt/fu03/lvzhen/miniconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
return fn(*args)
File "/mnt/fu03/lvzhen/miniconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
options, feed_dict, fetch_list, target_list, run_metadata)
File "/mnt/fu03/lvzhen/miniconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Paddings must be non-negative: 0 -49
[[{{node PadV2}}]]
[[{{node IteratorGetNext}}]]
[[{{node IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "test.py", line 93, in
mean_loss = retinanet.train_one_epoch(lr)
File "/mnt/fu03/lvzhen/test/RetinaNet-tensorflow/RetinaNet.py", line 492, in _train_detection_epoch
_, loss = self.sess.run([self.train_op, self.loss], feed_dict={self.lr: lr})
File "/mnt/fu03/lvzhen/miniconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
run_metadata_ptr)
File "/mnt/fu03/lvzhen/miniconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
feed_dict_tensor, options, run_metadata)
File "/mnt/fu03/lvzhen/miniconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
run_metadata)
File "/mnt/fu03/lvzhen/miniconda3/envs/deepfacelab/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Paddings must be non-negative: 0 -49
[[{{node PadV2}}]]
[[node IteratorGetNext (defined at /mnt/fu03/lvzhen/test/RetinaNet-tensorflow/RetinaNet.py:110) ]]
[[node IteratorGetNext (defined at /mnt/fu03/lvzhen/test/RetinaNet-tensorflow/RetinaNet.py:110) ]]

**Comment by lvZic** [comment]
all the problem disappeared. 
check https://github.com/tensorflow/models/issues/4798#issuecomment-406418855
